/**
 * Stage 1 — does this email need relaying at all?
 *
 * Runs on the SUBJECT LINE only, because that is all the mailbox export gives
 * us and all a person needs to make this call. Deliberately rules, not a
 * model: the incoming subjects are generated by DTI's ticketing system, so
 * they are template strings rather than prose. A regex matches a machine's
 * output exactly, and with 7 positive examples in the corpus there is nothing
 * to train on anyway.
 *
 * Order matters. Incident tickets are excluded FIRST, because Jay's rule is
 * that an incident ticket reporting an outage is somebody else's job and is
 * not relayed — so the ticket marker has to beat the outage wording.
 */

export interface TriageResult {
  abnormal: boolean;
  /** Shown to a reviewer, so it says what fired rather than just a verdict. */
  reason: string;
  /** How the rule matched, for the metrics view. */
  rule: 'notification' | 'outage_announcement' | 'incident_ticket' | 'no_match';
}

/** Service-desk ticket references. These are never relayed. */
const INCIDENT_TICKET = /\b(?:INC|RITM|TASK|CHG)\d{4,}\b/i;

/** The standard notice DTI sends. Six of the seven in the corpus are this. */
const NOTIFICATION = /\babnormal\s+events?\b/i;

/**
 * The seventh is an outage announcement that never says "abnormal". Only one
 * subject in all 603 matches this and it is that one — but it is kept narrow
 * on purpose, because widening it is what would start costing false alarms.
 */
const OUTAGE_ANNOUNCEMENT = /\b(?:outage|unavailable|degraded|is\s+down)\b/i;

export function triageSubject(subject: string): TriageResult {
  const text = subject ?? '';

  if (INCIDENT_TICKET.test(text)) {
    return {
      abnormal: false,
      reason: 'Service-desk incident ticket — handled by the incident process, not relayed.',
      rule: 'incident_ticket',
    };
  }

  if (NOTIFICATION.test(text)) {
    return {
      abnormal: true,
      reason: 'Standard DTI abnormal events notification.',
      rule: 'notification',
    };
  }

  if (OUTAGE_ANNOUNCEMENT.test(text)) {
    return {
      abnormal: true,
      reason: 'Announces an outage or loss of service without being an incident ticket.',
      rule: 'outage_announcement',
    };
  }

  return {
    abnormal: false,
    reason: 'Routine mail — nothing in the subject indicates an abnormal event.',
    rule: 'no_match',
  };
}
