"""
Train the final model and export it as plain JSON the app can run directly.

Logistic regression over L2-normalised Titan embeddings. It ties LinearSVC on
cross-validation (0.862 vs 0.863 macro F1, well inside one standard deviation)
and unlike the SVM it produces real probabilities - which the routing rule
depends on, so a confidence it cannot trust would be worse than none.

Exporting weights rather than shipping the .pkl means no Python at runtime:
the whole model is 8 rows of 1024 numbers plus 8 intercepts.

    python scripts/export_weights.py
"""
import json
from collections import Counter
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score
from sklearn.preprocessing import normalize


def load(name):
    rows = json.loads(Path(f'data/model/{name}.json').read_text(encoding='utf8'))
    vecs = json.loads(Path(f'data/model/{name}.vectors.json').read_text(encoding='utf8'))
    rows = [r for r in rows if r['id'] in vecs]
    X = normalize(np.array([vecs[r['id']] for r in rows], dtype=np.float32))
    return rows, X, np.array([r['category'] for r in rows])


train_rows, Xtr, ytr = load('train')
test_rows, Xte, yte = load('test')

# Unanimous panel rows are cleaner signal than 2-of-3 rows.
w = np.array([1.0 if r['agreement'] == 'unanimous' else 0.6 for r in train_rows])

clf = LogisticRegression(max_iter=3000, C=1.0, class_weight='balanced')
clf.fit(Xtr, ytr, sample_weight=w)

pred = clf.predict(Xte)
present = sorted(set(yte) | set(pred))
print(classification_report(yte, pred, labels=present, zero_division=0))
print(f'accuracy        {(pred == yte).mean():.3f}')
print(f'macro F1        {f1_score(yte, pred, average="macro", zero_division=0):.3f}')
maj = Counter(yte).most_common(1)[0]
print(f'baseline        {maj[1] / len(yte):.3f}  (always "{maj[0]}")')
lenient = sum(1 for p, r in zip(pred, test_rows)
              if p in (r.get('acceptableCategories') or [r['category']]))
print(f'lenient         {lenient / len(test_rows):.3f}  (any defensible label)')

out = Path('src/lib/model/weights.json')
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps({
    'engine': 'titan-logreg-v1',
    'embeddingModel': 'amazon.titan-embed-text-v2:0',
    'dimensions': int(Xtr.shape[1]),
    'trainedOn': int(Xtr.shape[0]),
    'categories': [str(c) for c in clf.classes_],
    'coefficients': [[round(float(v), 6) for v in row] for row in clf.coef_],
    'intercepts': [round(float(v), 6) for v in clf.intercept_],
}), encoding='utf8')
print(f'\nweights -> {out}  ({out.stat().st_size / 1024:.0f} KB)')

# ---- parity fixture -------------------------------------------------------
# The TypeScript port must reproduce these exactly. Vectors are embedded so the
# test is hermetic and does not depend on the multi-megabyte vector dumps.
proba = clf.predict_proba(Xte)
step = max(1, len(test_rows) // 40)
sample = list(range(0, len(test_rows), step))[:40]
fixture = Path('tests/fixtures/logreg-parity.json')
fixture.parent.mkdir(parents=True, exist_ok=True)
fixture.write_text(json.dumps({
    'note': 'Generated by scripts/export_weights.py. Expected output of the Python model.',
    'cases': [{
        'id': test_rows[i]['id'],
        'vector': [round(float(v), 7) for v in Xte[i]],
        'expectedCategory': str(pred[i]),
        'expectedConfidence': round(float(proba[i].max()), 6),
    } for i in sample],
}), encoding='utf8')
print(f'parity  -> {fixture}  ({len(sample)} cases, {fixture.stat().st_size / 1024:.0f} KB)')

# ---- evaluation for the app ----------------------------------------------
# The app was showing agreement on a 10-notice demo holdout, where every
# notice is worth 10 percentage points and the numbers look invented. The
# real evaluation lives here, so the interface can show it instead.
from sklearn.metrics import precision_recall_fscore_support

labels = sorted(set(yte) | set(pred))
prec, rec, f1, support = precision_recall_fscore_support(
    yte, pred, labels=labels, zero_division=0)

maj_label, maj_n = Counter(yte).most_common(1)[0]
Path('data/model/evaluation.json').write_text(json.dumps({
    'testedOn': int(len(yte)),
    'trainedOn': int(Xtr.shape[0]),
    'accuracy': float((pred == yte).mean()),
    'lenientAccuracy': float(lenient / len(test_rows)),
    'baseline': float(maj_n / len(yte)),
    'baselineLabel': str(maj_label),
    'macroF1': float(f1_score(yte, pred, average='macro', zero_division=0)),
    'perCategory': [
        {'category': str(c), 'precision': float(p), 'recall': float(r),
         'f1': float(f), 'support': int(s)}
        for c, p, r, f, s in zip(labels, prec, rec, f1, support)
    ],
}, indent=2), encoding='utf8')
print('evaluation -> data/model/evaluation.json')
